import os
import numpy as np
import matplotlib
matplotlib.use('Agg')  # Use non-GUI Agg backend for matplotlib
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

'''
NOTE:
- This script is designed to work together with msd-particle-position.py.
- The coordinates generated by this script serve as input for that script.
- However, it is generally NOT recommended to use these scripts for MSD analysis.
- It is better to use Gromacs built-in tool 'gmx msd' for reliable and efficient results.
'''

# Read PDB file and return coordinates for all models
def read_pdb(pdb_file):
    models = []
    with open(pdb_file, 'r') as f:
        model = []
        for line in f:
            if line.startswith("MODEL"):
                if model:
                    models.append(model)
                model = []
            if line.startswith("ATOM") or line.startswith("HETATM"):
                model.append(line)
        if model:
            models.append(model)
    return models

# Extract the coordinates of selected atoms from all models
def extract_coordinates(models, atom_indices):
    coordinates = {index: [] for index in atom_indices}
    for model in models:
        for line in model:
            parts = line.split()
            atom_index = int(parts[1])  # Get atom index
            if atom_index in atom_indices:
                x = float(parts[5])  # X coordinate (6th column)
                y = float(parts[6])  # Y coordinate (7th column)
                z = float(parts[7])  # Z coordinate (8th column)
                coordinates[atom_index].append([x, y, z])
    return coordinates

# Choose which particle indices to export
def choose_particles(models):
    particle_indices = []
    print("Please enter the particle indices to export (separate with spaces):")
    print("You can find particle indices in the corresponding .gro file.")
    
    input_indices = input("Enter indices: ").split()
    particle_indices = [int(idx) for idx in input_indices]
    return particle_indices

# Plot the 3D coordinates and save the plot as a PNG file
def plot_coordinates(coordinates, particle_index, output_dir):
    coords = np.array(coordinates[particle_index])
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.scatter(coords[:, 0], coords[:, 1], coords[:, 2], label=f'Atom {particle_index}')
    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_zlabel('Z')
    plt.title(f"3D Coordinates of Particle {particle_index}")
    
    plt.savefig(f"{output_dir}/{particle_index}.png")
    plt.close()

# Plot the overlay of all particle coordinates and save the plot as a PNG file
def plot_all_coordinates(all_coordinates, output_dir):
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    for particle_index, coords in all_coordinates.items():
        coords = np.array(coords)
        ax.scatter(coords[:, 0], coords[:, 1], coords[:, 2], label=f'Atom {particle_index}')
    
    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_zlabel('Z')
    plt.title("Overlay of All Particles' Coordinates")
    
    plt.savefig(f"{output_dir}/all_particles.png")
    plt.close()

# Save the coordinates of each particle to a TXT file
def save_coordinates_to_txt(coordinates, particle_index, output_dir):
    coords = np.array(coordinates[particle_index])
    np.savetxt(f"{output_dir}/{particle_index}.txt", coords, header="X Y Z", comments='')

def main():
    gro_file = "npt-400.gro"  # Modify with your gro file path
    pdb_file = "5zncl-traj.pdb"  # Modify with your pdb file path
    output_dir = "output"  # Output folder

    models = read_pdb(pdb_file)
    
    particle_indices = choose_particles(models)
    
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    coordinates = extract_coordinates(models, particle_indices)
    
    for particle_index in particle_indices:
        save_coordinates_to_txt(coordinates, particle_index, output_dir)
        plot_coordinates(coordinates, particle_index, output_dir)
    
    plot_all_coordinates(coordinates, output_dir)
    
    print("Processing completed. Results have been saved to the output folder.")

if __name__ == "__main__":
    main()
